// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGYd2o7NNWq72i61MycrTAJWa5hSGp7mk',
    appId: '1:81343272216:web:b12eb9f21e88db9e117a6d',
    messagingSenderId: '81343272216',
    projectId: 'magusb-4e1c9',
    authDomain: 'magusb-4e1c9.firebaseapp.com',
    databaseURL: 'https://magusb-4e1c9-default-rtdb.firebaseio.com',
    storageBucket: 'magusb-4e1c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwCsX6NMNOLgC-fzdjUrY8riQmbw7tsJQ',
    appId: '1:81343272216:android:bc0acc74fa6c6941117a6d',
    messagingSenderId: '81343272216',
    projectId: 'magusb-4e1c9',
    databaseURL: 'https://magusb-4e1c9-default-rtdb.firebaseio.com',
    storageBucket: 'magusb-4e1c9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGYd2o7NNWq72i61MycrTAJWa5hSGp7mk',
    appId: '1:81343272216:web:972514625812a802117a6d',
    messagingSenderId: '81343272216',
    projectId: 'magusb-4e1c9',
    authDomain: 'magusb-4e1c9.firebaseapp.com',
    databaseURL: 'https://magusb-4e1c9-default-rtdb.firebaseio.com',
    storageBucket: 'magusb-4e1c9.firebasestorage.app',
  );
}
